os: linux
dist: xenial

language: python
cache: pip
services:
  - redis

matrix:
  include:
    - env: TOXENV=lint
    - python: 3.6
      env: TOXENV=py36-django30-aioredislatest
    - python: 3.6
      env: TOXENV=py36-django30-aioredismaster
    - python: 3.7
      env: TOXENV=py37-django30-aioredislatest
    - python: 3.7
      env: TOXENV=py37-django30-aioredismaster
    - python: 3.8
      env: TOXENV=py38-django30-aioredislatest
    - python: 3.8
      env: TOXENV=py38-django30-aioredismaster
    - python: 3.6
      env: TOXENV=py36-django31-aioredislatest
    - python: 3.6
      env: TOXENV=py36-django31-aioredismaster
    - python: 3.7
      env: TOXENV=py37-django31-aioredislatest
    - python: 3.7
      env: TOXENV=py37-django31-aioredismaster
    - python: 3.8
      env: TOXENV=py38-django31-aioredislatest
    - python: 3.8
      env: TOXENV=py38-django31-aioredismaster
    - python: 3.6
      env: TOXENV=py36-djangomaster-aioredislatest
    - python: 3.6
      env: TOXENV=py36-djangomaster-aioredismaster
    - python: 3.7
      env: TOXENV=py37-djangomaster-aioredislatest
    - python: 3.7
      env: TOXENV=py37-djangomaster-aioredismaster
    - python: 3.8
      env: TOXENV=py38-djangomaster-aioredislatest
    - python: 3.8
      env: TOXENV=py38-djangomaster-aioredismaster
  allow_failures:
    - env: TOXENV=lint
      if: branch=master
    - env: TOXENV=py36-djangomaster-aioredislatest
    - env: TOXENV=py36-djangomaster-aioredismaster
    - env: TOXENV=py37-djangomaster-aioredislatest
    - env: TOXENV=py37-djangomaster-aioredismaster
    - env: TOXENV=py38-djangomaster-aioredislatest
    - env: TOXENV=py38-djangomaster-aioredismaster

install: pip install tox
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: E71Tbg2TNUKZMvCxw+FbEizJL/kwBd8PJ9Xg0Abnm1QBsaeOY8G0mq8HArwHeYlH/2485qRNVeXNfzY8fCQbG29cXhzUm7Bv+gCW3rqeQGKMPmRwEupQq4XB2xCzc8xlbhGk0OctT10jCu3ZZ5lyfKbEVYF06oSDjC3M5uS701+M41XjnHu2vufLbs9Dcc5W0yDRopLsgDxWsDuyaEf2guT0/NrbJ5r68TD8s+r681xJcoh4LqCuZw1vLlbvK0xoI0RxsTIKEyAwIX3CMZwuYKuk6i/bTsT5qPLvDQQqvTNYNMTEKR6yiRs9ZQEWCWpyfCM74J3YXxYYvejWk6Tc0kalzmqVkFCUubnJltdxWl6ZrJ7pRnauXddMPETTGAqvbrY+snP1pHDrXr74i0wiPXPcYuFgKXWzk7vUZ5TT8brvwKCUITP1kp59zvEFEtMvZdyC1me9d3rIzZGlItt/3XY6PeTYKyghlzHc+t0gy4UG1ZKyKvvku5XSQIT62a89ZQtPjb+9B8O1w9KvYLX17VR5O1vDOVAzSncFtZIXP3Qhm2pYM4vPGGSOXmPhutyRwalHGWWLX5Xw4pJMmUd+5xyDnaCNfAxxIb3JHXgGNfV21e7wRXhxRAy+esoxGuwQ2PExNMO5qwO/o3SX7+r6Qq33F7opSzI1aL1pbSBrXwM=
  on:
    tags: true
    repo: Andrew-Chen-Wang/django-async-redis
    python: 3.8
